### ISSUE TITLE
Spindown almost working

### ISSUE THREAD

**Issue by rmnmllr** [alxbr/SYNO-spindown#1]
Hey,
I'm sorry if this is the wrong place to ask this, but maybe others have the same issue. I found your repository through the synology-forum.de [here](https://www.synology-forum.de/threads/usb-festplatte-ruhezustand-klappt-nicht.86689/page-2#post-910387). Before installing your script, my external WD MyBook 8TB spined down but immediately spined up again.
Now after placing your script according to your readme my WD MyBook still does not go fully into sleep mode. The time between spinning down and up again increased slightly though, it is now between 10s and 30s. Bear in mind the hard disc is only there to do a Hyper backup in the middle of the night, no other purpose besides that.

- did you do anything else to your Synology that would let it sleep until it is really needed?
- also what is meant by "_The permission must be 755_"?
- did you do anything with the WD drive utilities?

Many thanks in advance!

**Comment by alxbr** [comment]
Hi @seentron,

when you access DSM via browser, My Book will always wake up (spin up). Keep it in mind :)

I've just disabled the power management for external usb drive(s) in DSM: Control Panel -> Hardware & Power -> HDD Hibernation -> Time: none            (you don't need it if the script is running).

If you put the script in /usr/local/etc/rc.d/, then please check the rights of the file in terminal (via telnet/ssh):
`admin@DS918plus:/usr/local/etc/rc.d$ ls -l`
`-rwxr-xr-x  1 root root 1502 Jan  3 20:57 spindown.sh`

If it does not have `x` , then run
`sudo chmod +x spindown.sh`

Don't forget to restart your synology disk station to run the script.

Regards,
Alex

PS: you can try to run
`synodisk --usbstandby /dev/sdq` 
or 
`synodisk --usbstandby /dev/sdr`
in terminal and see what happens.
May be you have some other application/service which try to access to your My Book in background...

**Comment by rmnmllr** [comment]
Hi Alex,

Thanks a lot for your reply!

I still had the power management thing enabled so I changed that to none as well. I watched it for a few days now, it seems the spin-down works better but still some random wake-ups (though the time between increased a lot). I assume therefore the Synology still accesses the external MyBook, although I don't know which process(es).

I tried the synodisk commands, it seems to force the sleep somehow or what does it do exactly? Would you mind pointing me to some documentation of the synodisk command or its options? (A couple Google searches didn't reveal much)

**Comment by alxbr** [comment]
Hi @seentron,

the synodisk command has a good help, just run it without parameter:

> ~# synodisk
> Copyright (c) 2003-2020 Synology Inc. All rights reserved.
> 
> Usage: synodisk (Version 25426)
> --partition	-d DEV_PATH Partition disk -t (s)ystem/(d)ata/(a)ll 
> --write_cache_set 
> --help     Show the usage
> --enum -t internal/ebox/cache/usb/sys Enumerate disks in internal or expansion box
> --info PATH         Query the disk information. Note [PATH] is omitted for single-disk plateform
> --detect_fs PATH    Detect the file system of a device
> --isssd DEV_PATH    Check the disk is ssd or not
> --standby DEV_PATH  Set [DEV_PATH] disk to standby 
> --usbstandby DEV_PATH  Set [DEV_PATH] usb disk to standby 
> --get_idle DEV_PATH Get [DEV_PATH] disk idle time 
> --read_temp DEV_PATH Get [DEV_PATH] disk temperature 
> --write_cache_get DEV_PATH Get [DEV_PATH] disk write cache status 
> --is_secure_erasing Check is any disk secure erasing 
> --get_location_form DEV_PATH get device location form(containerID-diskOrder) . e.g. 0-1
> --smart_info_get DEV_PATH get the smart information
> --m2-card-model-get DEV_PATH 	 get m.2 adapter card model
> --check-valid DEV_PATH 	 check whether the disk is valid
> --check -p PATH1,PATH2,... [-u] [-m mode] [-c] [-s size] [-r LOWERBOUND,UPPERBOUND]]
>        -u  Show details of correct block. (Default is disable)
>        -p  Set the location(s) of the target devices.
>        -m  Set the operation mode of the checking. The argument can be: 
>              'seq': Sequential writing mode. 
>              'jump' Jump writing mode. 
>        -c  Do checksum after writing. (Default is disable)
>        -s  Set the data block size in bytes based on the format [digital][unit]
>            where [digitial] is a integer and [unit] can be 'K','M' or 'G' 
>            representing kilo, meter and giga bytes. 
>            If the unit of the value is not assigned, 
>            the default unit is 'k'.
>        -r  Set the check range. The arguments LOWERBOUND and UPPERBOUND 
>            are also represented as [digital][unit]. (Default unit is 'k')
>            The default values of LOWERBOUND and UPPERBOUND are 0 and maximum disk size.
>            Note that LOWERBOUND must always smaller than UPPERBOUND.

With `iotop` you can try to get more info, which process access the external MyBook (you need to install `synogear` before):
`iotop -o -b -d 1 -P`

**Comment by rmnmllr** [comment]
Superb, thanks a lot for your help!
